version: "3.5"

services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/src
        ports:
            - 8505:8505
        networks:
            zmodules:
                aliases:
                    -  timeline

    jaeger:
        image: jaegertracing/all-in-one:1.56
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 4317:4317
            - 4318:4318
            - 14250:14250
            - 14268:14268
            - 14269:14269
            - 9411:9411
        networks:
            zmodules:
                aliases:
                    - tracing

networks:
  zmodules:
    driver: bridge
    name: zmodules
